// Course and graph types for PageRank algorithm
// Logic generated by Bolt.new

export interface Course {
  id: string;
  name: string;
  description?: string;
  credits?: number;
}

export interface Prerequisite {
  prerequisite: string;
  course: string;
}

export interface CourseNode extends Course {
  pageRank: number;
  inDegree: number;
  outDegree: number;
  prerequisites: string[];
  dependents: string[];
}

export interface GraphEdge {
  source: string;
  target: string;
}

export interface GraphData {
  nodes: CourseNode[];
  edges: GraphEdge[];
}

export interface PageRankResult {
  courseId: string;
  rank: number;
  score: number;
}